apiVersion: v1
kind: Service

metadata:
  name: trafficops-api
  labels:
    app: trafficops-api

spec:
  type: {{ .Values.api.service.type }}

  selector:
    app: trafficops-api

  ports:
    - name: http
      port: {{ .Values.api.service.port }}
      targetPort: 8000
      protocol: TCP
