apiVersion: v1
kind: Secret

metadata:
  name: trafficops-secret

type: Opaque

stringData:
  DB_USER: {{ .Values.secret.dbUser | quote }}
  DB_PASSWORD: {{ .Values.secret.dbPassword | quote }}
  RABBITMQ_USER: {{ .Values.secret.rabbitmqUser | quote }}
  RABBITMQ_PASSWORD: {{ .Values.secret.rabbitmqPassword | quote }}
