apiVersion: apps/v1
kind: Deployment

metadata:
  name: trafficops-sensor-simulator
  labels:
    app: trafficops-sensor-simulator

spec:
  replicas: {{ .Values.replicaCount.simulator }}

  selector:
    matchLabels:
      app: trafficops-sensor-simulator

  template:
    metadata:
      labels:
        app: trafficops-sensor-simulator

    spec:
      containers:
        - name: sensor-simulator

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          env:
            - name: API_URL
              value: "http://trafficops-api:{{ .Values.api.service.port }}/events"

          command:
            - python
            - src/sensor_simulator/main.py
