apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: trafficops

spec:
  replicas: 1

  selector:
    matchLabels:
      app: postgres

  template:
    metadata:
      labels:
        app: postgres

    spec:
      containers:
        - name: postgres
          image: postgres:18

          ports:
            - containerPort: 5432

          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: trafficops-config
                  key: DB_NAME

            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: trafficops-secret
                  key: DB_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: trafficops-secret
                  key: DB_PASSWORD

          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql

      volumes:
        - name: postgres-storage
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: trafficops

spec:
  selector:
    app: postgres

  ports:
    - port: 5432
      targetPort: 5432
