apiVersion: v1
kind: Secret
metadata:
  name: trafficops-secret
  namespace: trafficops

type: Opaque

stringData:
  DB_USER: admin
  DB_PASSWORD: admin
  RABBITMQ_USER: trafficops
  RABBITMQ_PASSWORD: trafficops
