apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: trafficops
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/rupeshchavan48391-lab/Trafficops.git
    targetRevision: main
    path: k8s

  destination:
    server: https://kubernetes.default.svc
    namespace: trafficops

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
